name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
        node-version: [16.x, 18.x, 20.x]
        include:
          # Test Node 14 only on Linux and Windows (not available for Apple Silicon)
          - os: ubuntu-latest
            node-version: 14.x
          - os: windows-latest
            node-version: 14.x
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Make script executable (Unix)
      if: runner.os != 'Windows'
      run: chmod +x project-tool.js
    
    - name: Check script syntax
      run: node -c project-tool.js
    
    - name: Test help command
      run: node project-tool.js --help
    
    - name: Test version command
      run: node project-tool.js --version
    
    - name: Create test project structure
      run: |
        mkdir -p test-project/src/components
        echo "console.log('test');" > test-project/src/index.js
        echo '{"name":"test-project","version":"1.0.0"}' > test-project/package.json
        echo "# Test Project" > test-project/README.md
    
    - name: List test project (Unix)
      if: runner.os != 'Windows'
      run: |
        echo "Test project structure:"
        ls -la test-project/
        ls -la test-project/src/
    
    - name: List test project (Windows)
      if: runner.os == 'Windows'
      run: |
        echo "Test project structure:"
        dir test-project
        dir test-project\src
    
    - name: Summary
      run: |
        echo "✅ Node.js ${{ matrix.node-version }} on ${{ matrix.os }}"
        echo "✅ Script syntax valid"
        echo "✅ Help command works"
        echo "✅ Version command works"
        echo "✅ Test completed successfully!"