# .github/workflows/test.yml
name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [12.x, 14.x, 16.x, 18.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Make script executable (Unix)
      if: runner.os != 'Windows'
      run: chmod +x project-tool.js
    
    - name: Test help command
      run: node project-tool.js --help || true
    
    - name: Check script syntax
      run: node -c project-tool.js
    
    - name: Create test project
      run: |
        mkdir -p test-project/src
        echo "console.log('test');" > test-project/src/index.js
        echo '{"name":"test"}' > test-project/package.json
    
    - name: Verify script runs
      run: |
        echo "Script syntax check passed"
        ls -la